version: '3'

services:
  dc1_node_1:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    volumes:
      - ./scylla/cassandra-rackdc.1.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    networks:
      public:
        ipv4_address: 192.168.100.11

  dc1_node_2:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    volumes:
      - ./scylla/cassandra-rackdc.1.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    networks:
      public:
        ipv4_address: 192.168.100.12

  dc1_node_3:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    volumes:
      - ./scylla/cassandra-rackdc.1.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    networks:
      public:
        ipv4_address: 192.168.100.13

  dc2_node_1:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    volumes:
      - ./scylla/cassandra-rackdc.2.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    networks:
      public:
        ipv4_address: 192.168.100.21

  dc2_node_2:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    volumes:
      - ./scylla/cassandra-rackdc.2.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    networks:
      public:
        ipv4_address: 192.168.100.22

  dc2_node_3:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    volumes:
      - ./scylla/cassandra-rackdc.2.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    networks:
      public:
        ipv4_address: 192.168.100.23
