version: '3'

services:
  dc1_node_1:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    volumes:
      - ./scylla/scylla.yaml:/etc/scylla/scylla.yaml:ro
      - ./scylla/cassandra-rackdc.1.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21 --listen-address 192.168.51.11 --broadcast-address 192.168.100.11 --broadcast-rpc-address 192.168.100.11
    networks:
      public:
        ipv4_address: 192.168.100.11
      dc1_private:
        ipv4_address: 192.168.51.11

  dc1_node_2:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    volumes:
      - ./scylla/scylla.yaml:/etc/scylla/scylla.yaml:ro
      - ./scylla/cassandra-rackdc.1.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21 --listen-address 192.168.51.12 --broadcast-address 192.168.100.12 --broadcast-rpc-address 192.168.100.12
    networks:
      public:
        ipv4_address: 192.168.100.12
      dc1_private:
        ipv4_address: 192.168.51.12

  dc1_node_3:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    volumes:
      - ./scylla/scylla.yaml:/etc/scylla/scylla.yaml:ro
      - ./scylla/cassandra-rackdc.1.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21 --listen-address 192.168.51.13 --broadcast-address 192.168.100.13 --broadcast-rpc-address 192.168.100.13
    networks:
      public:
        ipv4_address: 192.168.100.13
      dc1_private:
        ipv4_address: 192.168.51.13

  dc2_node_1:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    volumes:
      - ./scylla/scylla.yaml:/etc/scylla/scylla.yaml:ro
      - ./scylla/cassandra-rackdc.2.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21 --listen-address 192.168.52.21 --broadcast-address 192.168.100.21 --broadcast-rpc-address 192.168.100.21
    networks:
      public:
        ipv4_address: 192.168.100.21
      dc2_private:
        ipv4_address: 192.168.52.21

  dc2_node_2:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    volumes:
      - ./scylla/scylla.yaml:/etc/scylla/scylla.yaml:ro
      - ./scylla/cassandra-rackdc.2.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21 --listen-address 192.168.52.22 --broadcast-address 192.168.100.22 --broadcast-rpc-address 192.168.100.22
    networks:
      public:
        ipv4_address: 192.168.100.22
      dc2_private:
        ipv4_address: 192.168.52.22

  dc2_node_3:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    volumes:
      - ./scylla/scylla.yaml:/etc/scylla/scylla.yaml:ro
      - ./scylla/cassandra-rackdc.2.properties:/etc/scylla/cassandra-rackdc.properties:ro
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21 --listen-address 192.168.52.23 --broadcast-address 192.168.100.23 --broadcast-rpc-address 192.168.100.23
    networks:
      public:
        ipv4_address: 192.168.100.23
      dc2_private:
        ipv4_address: 192.168.52.23
